// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBewmY7OMWMzai-Pw1uqDnwvkbbM1k2yuI',
    appId: '1:505070127477:web:4bede371371a605c0b2b3c',
    messagingSenderId: '505070127477',
    projectId: 'flutter-firebase-app-c06ab',
    authDomain: 'flutter-firebase-app-c06ab.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-c06ab.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBewmY7OMWMzai-Pw1uqDnwvkbbM1k2yuI',
    appId: '1:505070127477:web:a9eb00b48e67c0ab0b2b3c',
    messagingSenderId: '505070127477',
    projectId: 'flutter-firebase-app-c06ab',
    authDomain: 'flutter-firebase-app-c06ab.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-c06ab.appspot.com',
  );
}
